### ISSUE TITLE
Everything works but webcam doesn't show up

### ISSUE THREAD

**Issue by DontRage** [olx268/OpenCore-macOS-XPS-9500#1]
Hi, first of all thank you very much. I have installed the OS and everything works other than the webcam. I can see under your checklist that the webcam is working but not sure why it's not working for me. I'm using your config.plist file you have provided. Any idea why I'm having this issue? Also on another note I can see under about that graphic card is detected but the animation on big sur are very laggy for me.

Kind regards

**Comment by olx268** [comment]
Hi, glad to hear that you successfully installed the OS! Please make sure that your webcam is activated in the BIOS and test it with https://webcamtests.com/ as i done, regarding Big Sur being laggy i don't have an idea as to why exactly. It might be Apple as they are moving from Intel Processors to their own inhouse M2 Chips and Apple is known to use software tricks to slowdown old systems. Can you please keep me updated with your troubleshooting? 

Kind regards

**Comment by DontRage** [comment]
I have checked the BIOS under integrated devices and I can see webcam is on. Also on my Windows 10 my webcam is functional. So far haven't found a soulition.
My device is XPS 9500 with 10875H with the latest BIOS and frimware.
I will update!

Thank you

**Comment by olx268** [comment]
Hi could you please check if the Webcam shows up in SysProfiler->USB section, otherwise you might have a different USB Layout and Webcam model as mine and you might need to perform some SSDT patching using USBinjectall.kext. You could also try https://phoboslab.org/log/2009/07/uvc-camera-control-for-mac-os-x to activate it. Regarding your GPU and lag, i'm pretty confident that it's the difference in models from mine as i have an Intel i7 10750H. Does your Hackintosh show the exact same VRAM as mine? 

Regards

**Comment by DontRage** [comment]
CPU shows as 2.3 GHz 8 core but VRAM is same.
As you said I think I need to do SSDT patching to resolve this.
Appreciate your help.

**Comment by olx268** [comment]
Glad to help! There are a few XPS 9500 models, some with touch and 4k and some 1080p and no touch. Webcam might be different. Happy patching!
